In [82]:
import pandas as pd

# 1. Read Data

In [101]:
def read_data (filename, filetype):
    '''
    Read data from file to pandas DataFrame
        filename, filetype: string
    '''
    if filetype == 'csv':
        return pd.read_csv(filename, index_col=0)
    if filetype == 'xls':
        return pd.read_excel(filename)
    if filetype == 'json':
        return pd.read_json(filename)

In [102]:
df = read_data('credit-data.csv', 'csv')

In [103]:
train, test = train_test_split(df, test_size = 0.2)

# 2. Explore Data

In [104]:
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,zipcode,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
PersonID,,,,,,,,,,,,
1,1,0.766127,45,60644,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,60637,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,60601,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,60601,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,60625,1,0.024926,63588.0,7,0,1,0,0.0

In [109]:
df.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,zipcode,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,0.066840,6.048438,52.295207,60648.810013,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.737413
std,0.249746,249.755371,14.771866,56.748197,4.192781,2037.818523,1.288045e+04,5.145951,4.169304,1.129771,4.155179,1.107021
min,0.000000,0.000000,0.000000,60601.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,60625.000000,0.000000,0.175074,3.903000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,60629.000000,0.000000,0.366508,6.600000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,60644.000000,0.000000,0.868254,7.400000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,60804.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [110]:
df.isnull().sum()

SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
zipcode                                 0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

# 3. Pre-Process Data

In [111]:
def fill_null(df, col_name, fill_method):
    '''
    Fill null values of the specified columnn in the dataframe
        col_name: string
        fill_method: 'mean', 'median'
    '''
    if fill_method == 'mean':
        df[col_name].fillna(value=df[col_name].mean(), inplace=True)  
    if fill_method == 'median':
        df[col_name].fillna(value=df[col_name].median(), inplace=True)
    return df

In [112]:
fill_null(df, 'MonthlyIncome', 'mean')
fill_null(df, 'NumberOfDependents', 'median')
df.isnull().sum()

SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
zipcode                                 0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

# 4. Generate Features/ Predictors

In [113]:
df

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,zipcode,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
PersonID,,,,,,,,,,,,
1,1,0.766127,45,60644,2,0.802982,9120.000000,13,0,6,0,2.0
2,0,0.957151,40,60637,0,0.121876,2600.000000,4,0,0,0,1.0
3,0,0.658180,38,60601,1,0.085113,3042.000000,2,1,0,0,0.0
4,0,0.233810,30,60601,0,0.036050,3300.000000,5,0,0,0,0.0
5,0,0.907239,49,60625,1,0.024926,63588.000000,7,0,1,0,0.0
6,0,0.213179,74,60629,0,0.375607,3500.000000,3,0,1,0,1.0
7,0,0.305682,57,60637,0,5710.000000,6670.221237,8,0,3,0,0.0
8,0,0.754464,39,60625,0,0.209940,3500.000000,8,0,0,0,0.0
9,0,0.116951,27,60804,0,46.000000,6670.221237,2,0,0,0,0.0
10,0,0.189169,57,60629,0,0.606291,23684.000000,9,0,4,0,2.0
11,0,0.644226,30,60637,0,0.309476,2500.000000,5,0,0,0,0.0
12,0,0.018798,51,60804,0,0.531529,6501.000000,7,0,2,0,2.0
13,0,0.010352,46,60644,0,0.298354,12454.000000,13,0,2,0,2.0
14,1,0.964673,40,60804,3,0.382965,13700.000000,9,3,1,1,2.0
15,0,0.019657,76,60657,0,477.000000,0.000000,6,0,1,0,0.0
16,0,0.548458,64,60629,0,0.209892,11362.000000,7,0,1,0,2.0
17,0,0.061086,78,60601,0,2058.000000,6670.221237,10,0,2,0,0.0
18,0,0.166284,53,60644,0,0.188274,8800.000000,7,0,0,0,0.0
19,0,0.221813,43,60601,0,0.527888,3280.000000,7,0,1,0,2.0
20,0,0.602794,25,60657,0,0.065868,333.000000,2,0,0,0,0.0
21,0,0.200923,43,60625,0,0.430046,12300.000000,10,0,2,0,0.0
22,1,0.025656,38,60629,0,0.475841,3000.000000,7,0,1,0,2.0
23,0,1.000000,39,60601,0,0.241104,2500.000000,4,0,0,0,0.0
24,0,0.075427,32,60629,0,0.085512,7916.000000,6,0,0,0,0.0
25,0,0.046560,58,60657,0,0.241622,2416.000000,9,0,1,0,0.0
26,1,0.392248,50,60618,0,1.595253,4676.000000,14,0,3,0,1.0
27,0,0.052436,58,60601,0,0.097672,8333.000000,22,0,1,0,0.0
28,0,0.034421,69,60644,0,0.042383,2500.000000,17,0,0,0,1.0
29,0,0.452516,24,60657,0,0.011761,3400.000000,1,0,0,0,0.0
30,0,0.392995,58,60625,2,0.436103,5500.000000,15,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149971,0,0.025449,58,60625,0,0.253855,15500.000000,7,0,2,0,2.0
149972,0,0.058001,83,60637,0,0.013997,5000.000000,6,0,0,0,0.0
149973,0,0.071273,42,60644,0,0.008638,6945.000000,3,0,0,0,1.0
149974,0,1.026395,44,60618,0,0.494819,5500.000000,7,0,1,0,1.0
149975,0,0.962721,61,60804,2,0.603479,5000.000000,11,0,1,0,0.0
149976,0,0.022088,58,60618,0,2716.000000,6670.221237,8,0,2,0,0.0
149977,0,0.000627,76,60637,0,60.000000,6670.221237,5,0,0,0,0.0
149978,0,0.236450,29,60601,0,349.000000,6670.221237,3,0,0,0,0.0
149979,0,0.917635,52,60625,2,0.259496,2500.000000,4,0,0,0,0.0
149980,1,0.224711,55,60804,0,0.057235,8700.000000,7,0,0,0,0.0
149981,0,0.067644,64,60657,0,0.254976,5525.000000,12,0,1,0,0.0
149982,0,0.810012,43,60601,0,0.121752,6849.000000,4,0,0,0,4.0
149983,0,0.021046,37,60804,0,0.250272,2760.000000,8,0,0,0,3.0
149984,0,0.002485,82,60629,0,0.000800,5000.000000,5,0,0,0,0.0
149985,0,0.037548,84,60629,0,25.000000,6670.221237,5,0,0,0,0.0
149986,0,0.954409,26,60637,0,0.324962,1950.000000,4,0,0,0,0.0
149987,0,0.168102,49,60644,0,0.080384,5000.000000,16,0,0,0,1.0
149988,0,1.000000,28,60625,0,0.055692,3249.000000,3,1,0,0,0.0
149989,0,0.902051,31,60657,1,0.347924,7515.000000,10,0,1,0,0.0
149990,0,0.013356,62,60625,0,0.001408,9233.000000,4,0,0,0,3.0
149991,0,0.055518,46,60618,0,0.609779,4335.000000,7,0,1,0,2.0
149992,0,0.104112,59,60601,0,0.477658,10316.000000,10,0,2,0,0.0
149993,0,0.871976,50,60618,0,4132.000000,6670.221237,11,0,1,0,3.0
149994,0,1.000000,22,60625,0,0.000000,820.000000,1,0,0,0,0.0
149995,0,0.385742,50,60625,0,0.404293,3400.000000,7,0,0,0,0.0
149996,0,0.040674,74,60637,0,0.225131,2100.000000,4,0,1,0,0.0
149997,0,0.299745,44,60625,0,0.716562,5584.000000,4,0,1,0,2.0
149998,0,0.246044,58,60625,0,3870.000000,6670.221237,18,0,1,0,0.0
149999,0,0.000000,30,60625,0,0.000000,5716.000000,4,0,0,0,0.0
150000,0,0.850283,64,60657,0,0.249908,8158.000000,8,0,2,0,0.0

In [114]:
def discretize_cont_var(df, col_name, num_bins, cut_type):
    '''
    Discretize a continuous variable of the DataFrame
        df: pandas DataFrame
        col_name, cut_type: string
        nnum_bins: integer
        labels: list of strings
    '''
    if cut_type == 'quantile':
        df[col_name +'_discretize'] = pd.qcut(df[col_name], num_bins)
    if cut_type == 'uniform':
        df[col_name +'_discretize'] = pd.cut(df[col_name], num_bins)
    return df

In [115]:
df = discretize_cont_var(df, 'age', num_bins=4, cut_type='uniform')
# df.groupby(['age_discretize']).count()

In [116]:
def binarize_categ_var(df, col_name):
    '''
    Take a categorical variable and create binary/dummy variables from it
        df: pandas DataFrame
        col_name: string, categorical variable to binarize
    '''
    dummies = pd.get_dummies(df[col_name])
    df = df.join(dummies)
    return df

In [117]:
df = binarize_categ_var(df, 'age_discretize')

In [118]:
df

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,zipcode,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,age_discretize,"(-0.109, 27.25]","(27.25, 54.5]","(54.5, 81.75]","(81.75, 109]"
PersonID,,,,,,,,,,,,,,,,,
1,1,0.766127,45,60644,2,0.802982,9120.000000,13,0,6,0,2.0,"(27.25, 54.5]",0,1,0,0
2,0,0.957151,40,60637,0,0.121876,2600.000000,4,0,0,0,1.0,"(27.25, 54.5]",0,1,0,0
3,0,0.658180,38,60601,1,0.085113,3042.000000,2,1,0,0,0.0,"(27.25, 54.5]",0,1,0,0
4,0,0.233810,30,60601,0,0.036050,3300.000000,5,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
5,0,0.907239,49,60625,1,0.024926,63588.000000,7,0,1,0,0.0,"(27.25, 54.5]",0,1,0,0
6,0,0.213179,74,60629,0,0.375607,3500.000000,3,0,1,0,1.0,"(54.5, 81.75]",0,0,1,0
7,0,0.305682,57,60637,0,5710.000000,6670.221237,8,0,3,0,0.0,"(54.5, 81.75]",0,0,1,0
8,0,0.754464,39,60625,0,0.209940,3500.000000,8,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
9,0,0.116951,27,60804,0,46.000000,6670.221237,2,0,0,0,0.0,"(-0.109, 27.25]",1,0,0,0
10,0,0.189169,57,60629,0,0.606291,23684.000000,9,0,4,0,2.0,"(54.5, 81.75]",0,0,1,0
11,0,0.644226,30,60637,0,0.309476,2500.000000,5,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
12,0,0.018798,51,60804,0,0.531529,6501.000000,7,0,2,0,2.0,"(27.25, 54.5]",0,1,0,0
13,0,0.010352,46,60644,0,0.298354,12454.000000,13,0,2,0,2.0,"(27.25, 54.5]",0,1,0,0
14,1,0.964673,40,60804,3,0.382965,13700.000000,9,3,1,1,2.0,"(27.25, 54.5]",0,1,0,0
15,0,0.019657,76,60657,0,477.000000,0.000000,6,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
16,0,0.548458,64,60629,0,0.209892,11362.000000,7,0,1,0,2.0,"(54.5, 81.75]",0,0,1,0
17,0,0.061086,78,60601,0,2058.000000,6670.221237,10,0,2,0,0.0,"(54.5, 81.75]",0,0,1,0
18,0,0.166284,53,60644,0,0.188274,8800.000000,7,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
19,0,0.221813,43,60601,0,0.527888,3280.000000,7,0,1,0,2.0,"(27.25, 54.5]",0,1,0,0
20,0,0.602794,25,60657,0,0.065868,333.000000,2,0,0,0,0.0,"(-0.109, 27.25]",1,0,0,0
21,0,0.200923,43,60625,0,0.430046,12300.000000,10,0,2,0,0.0,"(27.25, 54.5]",0,1,0,0
22,1,0.025656,38,60629,0,0.475841,3000.000000,7,0,1,0,2.0,"(27.25, 54.5]",0,1,0,0
23,0,1.000000,39,60601,0,0.241104,2500.000000,4,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
24,0,0.075427,32,60629,0,0.085512,7916.000000,6,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
25,0,0.046560,58,60657,0,0.241622,2416.000000,9,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
26,1,0.392248,50,60618,0,1.595253,4676.000000,14,0,3,0,1.0,"(27.25, 54.5]",0,1,0,0
27,0,0.052436,58,60601,0,0.097672,8333.000000,22,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
28,0,0.034421,69,60644,0,0.042383,2500.000000,17,0,0,0,1.0,"(54.5, 81.75]",0,0,1,0
29,0,0.452516,24,60657,0,0.011761,3400.000000,1,0,0,0,0.0,"(-0.109, 27.25]",1,0,0,0
30,0,0.392995,58,60625,2,0.436103,5500.000000,15,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149971,0,0.025449,58,60625,0,0.253855,15500.000000,7,0,2,0,2.0,"(54.5, 81.75]",0,0,1,0
149972,0,0.058001,83,60637,0,0.013997,5000.000000,6,0,0,0,0.0,"(81.75, 109]",0,0,0,1
149973,0,0.071273,42,60644,0,0.008638,6945.000000,3,0,0,0,1.0,"(27.25, 54.5]",0,1,0,0
149974,0,1.026395,44,60618,0,0.494819,5500.000000,7,0,1,0,1.0,"(27.25, 54.5]",0,1,0,0
149975,0,0.962721,61,60804,2,0.603479,5000.000000,11,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
149976,0,0.022088,58,60618,0,2716.000000,6670.221237,8,0,2,0,0.0,"(54.5, 81.75]",0,0,1,0
149977,0,0.000627,76,60637,0,60.000000,6670.221237,5,0,0,0,0.0,"(54.5, 81.75]",0,0,1,0
149978,0,0.236450,29,60601,0,349.000000,6670.221237,3,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
149979,0,0.917635,52,60625,2,0.259496,2500.000000,4,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
149980,1,0.224711,55,60804,0,0.057235,8700.000000,7,0,0,0,0.0,"(54.5, 81.75]",0,0,1,0
149981,0,0.067644,64,60657,0,0.254976,5525.000000,12,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
149982,0,0.810012,43,60601,0,0.121752,6849.000000,4,0,0,0,4.0,"(27.25, 54.5]",0,1,0,0
149983,0,0.021046,37,60804,0,0.250272,2760.000000,8,0,0,0,3.0,"(27.25, 54.5]",0,1,0,0
149984,0,0.002485,82,60629,0,0.000800,5000.000000,5,0,0,0,0.0,"(81.75, 109]",0,0,0,1
149985,0,0.037548,84,60629,0,25.000000,6670.221237,5,0,0,0,0.0,"(81.75, 109]",0,0,0,1
149986,0,0.954409,26,60637,0,0.324962,1950.000000,4,0,0,0,0.0,"(-0.109, 27.25]",1,0,0,0
149987,0,0.168102,49,60644,0,0.080384,5000.000000,16,0,0,0,1.0,"(27.25, 54.5]",0,1,0,0
149988,0,1.000000,28,60625,0,0.055692,3249.000000,3,1,0,0,0.0,"(27.25, 54.5]",0,1,0,0
149989,0,0.902051,31,60657,1,0.347924,7515.000000,10,0,1,0,0.0,"(27.25, 54.5]",0,1,0,0
149990,0,0.013356,62,60625,0,0.001408,9233.000000,4,0,0,0,3.0,"(54.5, 81.75]",0,0,1,0
149991,0,0.055518,46,60618,0,0.609779,4335.000000,7,0,1,0,2.0,"(27.25, 54.5]",0,1,0,0
149992,0,0.104112,59,60601,0,0.477658,10316.000000,10,0,2,0,0.0,"(54.5, 81.75]",0,0,1,0
149993,0,0.871976,50,60618,0,4132.000000,6670.221237,11,0,1,0,3.0,"(27.25, 54.5]",0,1,0,0
149994,0,1.000000,22,60625,0,0.000000,820.000000,1,0,0,0,0.0,"(-0.109, 27.25]",1,0,0,0
149995,0,0.385742,50,60625,0,0.404293,3400.000000,7,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
149996,0,0.040674,74,60637,0,0.225131,2100.000000,4,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
149997,0,0.299745,44,60625,0,0.716562,5584.000000,4,0,1,0,2.0,"(27.25, 54.5]",0,1,0,0
149998,0,0.246044,58,60625,0,3870.000000,6670.221237,18,0,1,0,0.0,"(54.5, 81.75]",0,0,1,0
149999,0,0.000000,30,60625,0,0.000000,5716.000000,4,0,0,0,0.0,"(27.25, 54.5]",0,1,0,0
150000,0,0.850283,64,60657,0,0.249908,8158.000000,8,0,2,0,0.0,"(54.5, 81.75]",0,0,1,0

# 5. Build Classifier

In [119]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [120]:
def split_data(df, X, y, test_size):
    '''
    Split data into training and test sets
        df: Pandas DataFrame
        X: array of string, features
        y: string, outcome variable
        test_size: proportion of the total data used as test dataset

    '''
    X_train, X_test, y_train, y_test  = train_test_split(df[X], df[y], test_size=test_size)
    return X_train, X_test, y_train, y_test

In [121]:
y = 'SeriousDlqin2yrs'
cols = list(df.columns.values)
X = [x for x in cols if x != y]

In [122]:
X_train, X_test, y_train, y_test = split_data(df, X, y, 0.2)

In [123]:
def test_model(X_train, y_train, features, method):
    '''
    Build classifiers chosen by the user
        X_train, y_train: Pandas DataFrame
        features: list of strings, variables we care about
        method: LogisticRegression(), KNeighborsClassifier(), DecisionTreeClassifier()
    '''
    X = X_train[features]
    y = y_train
    return method.fit(X, y)

In [124]:
df.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'zipcode', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio',
       'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans',
       'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines',
       'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents',
       'age_discretize', '(-0.109, 27.25]', '(27.25, 54.5]', '(54.5, 81.75]',
       '(81.75, 109]'],
      dtype='object')

In [127]:
features = ['RevolvingUtilizationOfUnsecuredLines', 'age',
       'zipcode', 'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio',
       'MonthlyIncome', 'NumberOfOpenCreditLinesAndLoans',
       'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines',
       'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfDependents',
        '(-0.109, 27.25]', '(27.25, 54.5]', '(54.5, 81.75]',
       '(81.75, 109]']

In [128]:
test_model(X_train, y_train, features, DecisionTreeClassifier())

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [131]:
def predict_model(X_train, y_train, X_test, y, features, method):
    '''
    Predict outcomes for test data based on the chosen classifier, and write to csv file
        X_test: test pandas DataFrame
        y: string, outcome variable name, 'SeriousDlqin2yrs'
        features: list of strings, variables we care about
        method: LogisticRegression(), KNeighborsClassifier(), DecisionTreeClassifier()
    '''
    method.fit(X_train[features], y_train)
    X = X_test[features]
    y_pred = method.predict(X)
    df_pred = X_test
    df_pred[y] = y_pred
    df_pred.to_csv('predictions.csv', header=True)

In [133]:
predict_model(X_train, y_train, X_test, y, features, DecisionTreeClassifier())

# 6. Evaluate Classifier

In [134]:
from sklearn import metrics

In [141]:
def eval_model(X_train, y_train, X_test, y_test, features, method):
    method.fit(X_train[features], y_train)
    X = X_test[features]
    y_pred = method.predict(X)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    recall = metrics.recall_score(y_test, y_pred)
    precision = metrics.precision_score(y_test, y_pred)
    print('Accuracy score is: {}'.format(accuracy))
    print('Recall score is: {}'.format(recall))
    print('Precision score is: {}'.format(precision))

In [142]:
eval_model(X_train, y_train, X_test, y_test, features, LogisticRegression())

Accuracy score is: 0.9317
Recall score is: 0.0078125
Precision score is: 0.48484848484848486